name : Golang web
on: 
    push:
        branches:
        - 'v1.0'
        tags:
        - 'latest'

jobs: 
  ci:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

